from typing import Iterable, List, Optional, Sequence, Tuple, Union

__version__: str

DeviceTypeStr = str  # "SQLITE" | "SQLITE_STORE" | "STREAMING" | "DUCKDB" | "DUCKDB_STORE"
DstTypeStr = str     # "SQLITE" | "DUCKDB" | "POSTGRES"
DstSyncModeStr = str # "CONSOLIDATION" | "REPLICATION"

ParamValue = Union[None, bool, int, float, str, bytes]
ParamSeq = Sequence[ParamValue]
Row = Tuple[ParamValue, ...]


class DestinationOptions:
    dst_type: DstTypeStr
    dst_connection_string: str
    dst_database: Optional[str]
    dst_schema: Optional[str]
    dst_sync_mode: DstSyncModeStr

    def __init__(
        self,
        dst_type: DstTypeStr,
        dst_connection_string: str,
        dst_database: Optional[str] = None,
        dst_schema: Optional[str] = None,
        dst_sync_mode: DstSyncModeStr = "CONSOLIDATION",
    ) -> None: ...


def initialize(
    device_type: DeviceTypeStr,
    device_name: str,
    db_path: str,
    destination: Optional[DestinationOptions] = None,
    config_path: Optional[str] = None,
) -> None: ...


def await_sync(db_path: str, timeout_seconds: float) -> None: ...


class Connection:
    @staticmethod
    def open(db_path: str) -> "Connection": ...
    @staticmethod
    def initialize(db_path: str) -> "Connection": ...
    @staticmethod
    def open_with_config(conf_path: str) -> "Connection": ...
    @staticmethod
    def initialize_with_config(conf_path: str) -> "Connection": ...

    def execute(self, sql: str, params: Optional[ParamSeq] = None) -> int: ...
    def query(self, sql: str, params: Optional[ParamSeq] = None) -> List[Row]: ...
    def prepare(self, sql: str) -> "Statement": ...
    def set_auto_commit(self, auto_commit: bool) -> None: ...
    def get_auto_commit(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Connection": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...


class Statement:
    def execute(self, params: Optional[ParamSeq] = None) -> int: ...
    def query(self, params: Optional[ParamSeq] = None) -> List[Row]: ...
    def add_batch(self, params: ParamSeq) -> None: ...
    def clear_batch(self) -> None: ...
    def execute_batch(self) -> List[int]: ...


class DuckDBConnection:
    @staticmethod
    def open(db_path: str) -> "DuckDBConnection": ...
    @staticmethod
    def initialize(db_path: str) -> "DuckDBConnection": ...
    @staticmethod
    def open_with_config(conf_path: str) -> "DuckDBConnection": ...
    @staticmethod
    def initialize_with_config(conf_path: str) -> "DuckDBConnection": ...

    def execute(self, sql: str, params: Optional[ParamSeq] = None) -> int: ...
    def query(self, sql: str, params: Optional[ParamSeq] = None) -> List[Row]: ...
    def prepare(self, sql: str) -> "DuckDBStatement": ...
    def set_auto_commit(self, auto_commit: bool) -> None: ...
    def get_auto_commit(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "DuckDBConnection": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...


class DuckDBStatement:
    def execute(self, params: Optional[ParamSeq] = None) -> int: ...
    def query(self, params: Optional[ParamSeq] = None) -> List[Row]: ...
    def add_batch(self, params: ParamSeq) -> None: ...
    def clear_batch(self) -> None: ...
    def execute_batch(self) -> List[int]: ...
