//! Device integration tests.
//!
//! These tests are direct ports of the SQLite and DuckDB unit tests in
//! `synclite-logger-java/logger/src/test/java/io/synclite/logger/`,
//! adapted to the SyncLite-wrapped backend APIs in
//! `synclite::rusqlite` and `synclite::duckdb`.
//!
//! Layout alignment with the JUnit tests
//! (`DerbyAppenderTest`, `DerbyStoreAPITest`, etc.):
//!
//! - `testHome = ~/synclite/test/`
//! - `testDbPath = testHome/db/<TestName>/<device>.db` (per-test, wiped
//!   in `setUp`)
//! - `testStageDir = testHome/stageDir` (SHARED across tests; only the
//!   per-device `synclite-<device>-*` subdirs get cleaned)
//! - `testConfigPath = testDbPath.getParent()/synclite_logger.conf`
//!
//! Device names carry a `-rust` suffix so artifacts can't be confused
//! with artifacts generated by other SDKs if both run under the same
//! `~/synclite/test/` tree.
//!
//! Both ports write segments as `<N>.sqllog` inside a per-device
//! `synclite-<device>-<uuid>/` stage subdirectory.

use std::fs;
use std::path::{Path, PathBuf};

use duckdb::Connection as DuckConnection;
use rusqlite::Connection;
use synclite_core::record::ArgValue;
use synclite_core::DeviceType;
use synclite_db_traits::Row;
use synclite::{duckdb as sl_duckdb, rusqlite as sl_rusqlite, Logger};

// --------------------------------------------------------------------------
// Test scaffolding
// --------------------------------------------------------------------------

/// `~/synclite/test/` — matches the Java JUnit `testHome`.
fn test_home() -> PathBuf {
    let home = std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir);
    home.join("synclite").join("test")
}

fn inferred_device_type(device_name: &str, engine: &str) -> &'static str {
    if device_name.contains("stream") {
        return "STREAMING";
    }
    match (engine.to_ascii_lowercase().as_str(), device_name.contains("store")) {
        ("sqlite", true) => "SQLITE_STORE",
        ("sqlite", false) => "SQLITE",
        ("duckdb", true) => "DUCKDB_STORE",
        ("duckdb", false) => "DUCKDB",
        _ => panic!("unsupported engine: {engine}"),
    }
}

fn rm_rf(p: &Path) {
    let _ = fs::remove_dir_all(p);
}

/// Common test setup:
///   * wipe `testHome/db/<TestName>/`
///   * wipe any prior `testHome/stageDir/synclite-<device>-*` subdirs
///   * (re-)create both directories
///   * write `synclite_logger.conf` next to the DB
///
/// With `with_target=true`, a per-test `target/` dir under the DB dir
/// becomes the FS shipper destination for non-layout scenarios.
/// Layout-focused tests keep finalized segments under the device stage
/// subdir inside `testHome/stageDir`.
struct Workspace {
    device_name: String,
    device_type: DeviceType,
    stage: PathBuf,
    db_path: PathBuf,
    target: Option<PathBuf>,
    conf: PathBuf,
}

impl Workspace {
    fn new(test_name: &str, device_name: &str, engine: &str, with_target: bool) -> Self {
        let sanitized_device_name = {
            let s: String = device_name
                .chars()
                .filter(|ch| ch.is_ascii_alphanumeric())
                .collect();
            if s.is_empty() { "device".to_string() } else { s }
        };
        let test_home = test_home();
        let stage = test_home.join("stageDir");
        // Match the Java test layout under ~/synclite/test/db/<TestName>/ while
        // keeping Rust-created artifacts distinct via the -rust device suffix.
        let db_dir = test_home.join("db").join(test_name);
        let ext = if engine.eq_ignore_ascii_case("duckdb") { "duckdb" } else { "db" };
        let db_path = db_dir.join(format!("{device_name}.{ext}"));
        let target = if with_target { Some(db_dir.join("target")) } else { None };
        let conf = db_dir.join("synclite_logger.conf");
        let device_type = inferred_device_type(device_name, engine)
            .parse::<DeviceType>()
            .unwrap();

        // Wipe per-test DB dir entirely.
        rm_rf(&db_dir);
        // In the shared stageDir, wipe only this device's subdirs.
        let prefix = format!("synclite-{sanitized_device_name}-");
        if stage.exists() {
            if let Ok(entries) = fs::read_dir(&stage) {
                for entry in entries.flatten() {
                    if entry.file_name().to_string_lossy().starts_with(&prefix) {
                        rm_rf(&entry.path());
                    }
                }
            }
        }

        fs::create_dir_all(&stage).unwrap();
        fs::create_dir_all(&db_dir).unwrap();
        if let Some(t) = &target {
            fs::create_dir_all(t).unwrap();
        }

        let mut body = format!(
            "device-name={sanitized_device_name}\n\
             db-engine={engine}\n\
             device-type={}\n\
             db-path={}\n\
             local-data-stage-directory={}\n",
            device_type,
            db_path.display().to_string().replace('\\', "/"),
            stage.display().to_string().replace('\\', "/"),
        );
        if let Some(t) = &target {
            body.push_str(&format!(
                "destination-fs-target-dir={}\n",
                t.display().to_string().replace('\\', "/")
            ));
        }
        fs::write(&conf, body).unwrap();

        Self {
            device_name: sanitized_device_name,
            device_type,
            stage,
            db_path,
            target,
            conf,
        }
    }

    /// Locate the `synclite-<device>-<uuid>/` stage subdir created on
    /// first open. Panics if it does not yet exist.
    fn stage_subdir(&self) -> PathBuf {
        let prefix = format!("synclite-{}-", self.device_name);
        for entry in fs::read_dir(&self.stage).unwrap() {
            let entry = entry.unwrap();
            if entry.file_name().to_string_lossy().starts_with(&prefix) {
                return entry.path();
            }
        }
        panic!(
            "no stage subdir matching {prefix}* under {}",
            self.stage.display()
        )
    }

    /// `<db_path>.synclite/` device home directory.
    fn device_home(&self) -> PathBuf {
        format!("{}.synclite", self.db_path.display()).into()
    }

    fn sqlite_shadow_schema(&self) -> PathBuf {
        self.device_home().join(format!(
            "{}.sqlite",
            self.db_path.file_name().unwrap().to_string_lossy()
        ))
    }
}

enum TestConnection {
    Sqlite(sl_rusqlite::Connection),
    DuckDb(sl_duckdb::Connection),
}

enum TestStatement<'a> {
    Sqlite(sl_rusqlite::Statement<'a>),
    DuckDb(sl_duckdb::Statement<'a>),
}

impl TestConnection {
    fn set_auto_commit(&mut self, auto_commit: bool) {
        match self {
            Self::Sqlite(conn) => conn.set_auto_commit(auto_commit),
            Self::DuckDb(conn) => conn.set_auto_commit(auto_commit),
        }
    }

    fn execute(&mut self, sql: &str, params: &[ArgValue]) -> synclite_core::Result<u64> {
        match self {
            Self::Sqlite(conn) => conn.execute(sql, params),
            Self::DuckDb(conn) => conn.execute(sql, params),
        }
    }

    fn execute_unlogged(&mut self, sql: &str, params: &[ArgValue]) -> synclite_core::Result<u64> {
        match self {
            Self::Sqlite(conn) => conn.execute_unlogged(sql, params),
            Self::DuckDb(conn) => conn.execute_unlogged(sql, params),
        }
    }

    fn query(&mut self, sql: &str, params: &[ArgValue]) -> synclite_core::Result<Vec<Row>> {
        match self {
            Self::Sqlite(conn) => conn.query(sql, params),
            Self::DuckDb(conn) => conn.query(sql, params),
        }
    }

    fn prepare<'a>(&'a mut self, sql: &str) -> TestStatement<'a> {
        match self {
            Self::Sqlite(conn) => TestStatement::Sqlite(conn.prepare(sql).unwrap()),
            Self::DuckDb(conn) => TestStatement::DuckDb(conn.prepare(sql).unwrap()),
        }
    }

    fn commit(&mut self) -> synclite_core::Result<()> {
        match self {
            Self::Sqlite(conn) => conn.commit(),
            Self::DuckDb(conn) => conn.commit(),
        }
    }

    fn rollback(&mut self) -> synclite_core::Result<()> {
        match self {
            Self::Sqlite(conn) => conn.rollback(),
            Self::DuckDb(conn) => conn.rollback(),
        }
    }

    fn close(self) -> synclite_core::Result<()> {
        match self {
            Self::Sqlite(conn) => conn.close(),
            Self::DuckDb(conn) => conn.close(),
        }
    }
}

impl<'a> TestStatement<'a> {
    fn add_batch(&mut self, params: &[ArgValue]) {
        match self {
            Self::Sqlite(stmt) => stmt.add_batch(params),
            Self::DuckDb(stmt) => stmt.add_batch(params),
        }
    }

    fn execute_batch(&mut self) -> synclite_core::Result<Vec<u64>> {
        match self {
            Self::Sqlite(stmt) => stmt.execute_batch(),
            Self::DuckDb(stmt) => stmt.execute_batch(),
        }
    }
}

fn open_logger(ws: &Workspace) -> TestConnection {
    Logger::initialize_with_config_path(ws.device_type, &ws.db_path, &ws.conf).unwrap();
    if ws.db_path.extension().and_then(|s| s.to_str()) == Some("duckdb") {
        TestConnection::DuckDb(sl_duckdb::Connection::open_with_config(&ws.conf).unwrap())
    } else {
        TestConnection::Sqlite(sl_rusqlite::Connection::open_with_config(&ws.conf).unwrap())
    }
}

fn as_i64(v: &ArgValue) -> i64 {
    match v {
        ArgValue::Int(n) => *n,
        other => panic!("expected Int, got {other:?}"),
    }
}

fn as_text(v: &ArgValue) -> &str {
    match v {
        ArgValue::Text(s) => s.as_str(),
        other => panic!("expected Text, got {other:?}"),
    }
}

fn count(logger: &mut TestConnection, table: &str) -> i64 {
    let rows: Vec<Row> = logger
        .query(&format!("SELECT COUNT(*) FROM {table}"), &[])
        .unwrap();
    as_i64(&rows[0][0])
}

fn assert_execute_err_contains(logger: &mut TestConnection, sql: &str, expected_substr: &str) {
    let err = logger
        .execute(sql, &[])
        .expect_err("statement should be rejected");
    let msg = err.to_string();
    assert!(
        msg.contains(expected_substr),
        "expected error containing '{expected_substr}', got '{msg}'"
    );
}

fn seed_preexisting_user_db(ws: &Workspace, table_name: &str) {
    let ddl = format!("CREATE TABLE {table_name} (id INTEGER PRIMARY KEY, name TEXT)");
    let ins1 = format!("INSERT INTO {table_name} (id, name) VALUES (1, 'pre-1')");
    let ins2 = format!("INSERT INTO {table_name} (id, name) VALUES (2, 'pre-2')");
    if ws.db_path.extension().and_then(|s| s.to_str()) == Some("duckdb") {
        let c = DuckConnection::open(&ws.db_path).unwrap();
        c.execute(&ddl, []).unwrap();
        c.execute(&ins1, []).unwrap();
        c.execute(&ins2, []).unwrap();
    } else {
        let c = Connection::open(&ws.db_path).unwrap();
        c.execute(&ddl, []).unwrap();
        c.execute(&ins1, []).unwrap();
        c.execute(&ins2, []).unwrap();
    }
}

fn backup_row_count_for_table(backup_path: &Path, table_name: &str) -> i64 {
    let c = Connection::open(backup_path).unwrap();
    c.query_row(&format!("SELECT COUNT(*) FROM {table_name}"), [], |r| r.get(0))
        .unwrap()
}

fn preexisting_data_init_backup_and_logging_core(engine: &str, device_name: &str, test_name: &str) {
    let ws = Workspace::new(test_name, device_name, engine, false);
    let table_name = "t_preexisting";
    seed_preexisting_user_db(&ws, table_name);

    let mut logger = open_logger(&ws);
    assert_eq!(count(&mut logger, table_name), 2);
    logger
        .execute(
            &format!("INSERT INTO {table_name} (id, name) VALUES (?, ?)"),
            &[ArgValue::Int(3), ArgValue::Text("post-init".into())],
        )
        .unwrap();
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, table_name), 3);
    logger.close().unwrap();

    let stage_subdir = ws.stage_subdir();
    let backup = stage_subdir.join(format!(
        "{}.synclite.backup",
        ws.db_path.file_name().unwrap().to_string_lossy()
    ));
    assert!(backup.exists(), "backup file missing: {}", backup.display());
    assert_eq!(
        backup_row_count_for_table(&backup, table_name),
        2,
        "backup must contain preexisting rows captured at init"
    );

    let seg = locate_segment(&ws);
    assert_eq!(
        segment_and_txn_ci_count_starting_with(&seg, &format!("INSERT INTO {table_name}")),
        1,
        "only post-init INSERT should be logged"
    );
}

/// Locate the most recent shipped/local segment.
fn locate_segment(ws: &Workspace) -> PathBuf {
    try_locate_segment(ws).unwrap_or_else(|| {
        let dir = ws.target.clone().unwrap_or_else(|| ws.stage_subdir());
        panic!(
            "no non-empty <N>.sqllog segment found in {}",
            dir.display()
        )
    })
}

fn try_locate_segment(ws: &Workspace) -> Option<PathBuf> {
    let dir = ws.target.clone().unwrap_or_else(|| ws.stage_subdir());
    let mut best: Option<(u64, PathBuf)> = None;
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let entry = entry.unwrap();
        let name = entry.file_name().to_string_lossy().to_string();
        if let Some(num_str) = name.strip_suffix(".sqllog") {
            if let Ok(n) = num_str.parse::<u64>() {
                let path = entry.path();
                // Last shipped segment means the highest sequence file that
                // actually carries commandlog rows.
                if segment_max_commit_id_opt(&path).is_some()
                    && best.as_ref().map_or(true, |(b, _)| n >= *b)
                {
                    best = Some((n, path));
                }
            }
        }
    }
    best.map(|(_, p)| p)
}

fn segment_max_commit_id_opt(seg: &Path) -> Option<i64> {
    let c = Connection::open(seg).unwrap();
    c.query_row("SELECT MAX(commit_id) FROM commandlog", [], |r| {
        r.get::<_, Option<i64>>(0)
    })
    .unwrap()
}

/// `MAX(commit_id) FROM commandlog` for the given segment:
/// segments carry commit ids on `commandlog` rows; there is no
/// `synclite_txn` table inside a segment.
fn segment_max_commit_id(seg: &Path) -> i64 {
    segment_max_commit_id_opt(seg).unwrap_or_else(|| {
        panic!(
            "segment {} has no commandlog rows (MAX(commit_id) is NULL)",
            seg.display()
        )
    })
}

/// `MAX(commit_id)` over all `<N>.sqllog` files in this test workspace.
fn workspace_max_commit_id(ws: &Workspace) -> i64 {
    let dir = ws.target.clone().unwrap_or_else(|| ws.stage_subdir());
    let mut best = i64::MIN;
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let entry = entry.unwrap();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.ends_with(".sqllog") {
            if let Some(commit_id) = segment_max_commit_id_opt(&entry.path()) {
                best = best.max(commit_id);
            }
        }
    }
    assert!(best > 0, "no commit ids found under {}", dir.display());
    best
}

/// The latest segment (`locate_segment`) must carry the global max
/// commit id for the workspace.
fn assert_latest_segment_carries_max_commit_id(ws: &Workspace) {
    let latest = locate_segment(ws);
    let latest_commit = segment_max_commit_id(&latest);
    let global_max = workspace_max_commit_id(ws);
    assert_eq!(
        latest_commit,
        global_max,
        "latest segment {} commit_id {} != global max {}",
        latest.display(),
        latest_commit,
        global_max
    );
}

fn remove_fate_sql_for_commit(seg: &Path, commit_id: i64) {
    let c = Connection::open(seg).unwrap();
    c.execute(
        "DELETE FROM commandlog WHERE commit_id = ?1 AND (sql = 'COMMIT' OR sql = 'ROLLBACK')",
        [commit_id],
    )
    .unwrap();
}

fn set_user_synclite_txn_commit_id(ws: &Workspace, commit_id: i64) {
    if ws.db_path.extension().and_then(|s| s.to_str()) == Some("duckdb") {
        let c = DuckConnection::open(&ws.db_path).unwrap();
        c.execute("UPDATE synclite_txn SET commit_id = ?", [commit_id])
            .unwrap();
    } else {
        let c = Connection::open(&ws.db_path).unwrap();
        c.execute("UPDATE synclite_txn SET commit_id = ?1", [commit_id])
            .unwrap();
    }
}

fn user_db_synclite_txn_commit_id(ws: &Workspace) -> i64 {
    if ws.db_path.extension().and_then(|s| s.to_str()) == Some("duckdb") {
        let c = DuckConnection::open(&ws.db_path).unwrap();
        c.query_row("SELECT MAX(commit_id) FROM synclite_txn", [], |r| r.get(0))
            .unwrap()
    } else {
        let c = Connection::open(&ws.db_path).unwrap();
        c.query_row("SELECT MAX(commit_id) FROM synclite_txn", [], |r| r.get(0))
            .unwrap()
    }
}

fn assert_synclite_txn_matches_latest_segment(ws: &Workspace) {
    let latest_seg_commit = segment_max_commit_id(&locate_segment(ws));
    let user_commit = user_db_synclite_txn_commit_id(ws);
    assert_eq!(
        user_commit,
        latest_seg_commit,
        "synclite_txn.commit_id {} must match latest segment commit_id {}",
        user_commit,
        latest_seg_commit
    );
}

fn segment_commandlog_count_for(seg: &Path, commit_id: i64) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row(
        "SELECT COUNT(*) FROM commandlog WHERE commit_id = ?1",
        [commit_id],
        |r| r.get(0),
    )
    .unwrap()
}

fn segment_commandlog_count_starting_with(seg: &Path, keyword: &str) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row(
        "SELECT COUNT(*) FROM commandlog WHERE sql LIKE ?1",
        [format!("{keyword}%")],
        |r| r.get(0),
    )
    .unwrap()
}

fn segment_commandlog_ci_count_starting_with(seg: &Path, keyword: &str) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row(
        "SELECT COUNT(*) FROM commandlog WHERE sql IS NOT NULL AND lower(sql) LIKE lower(?1)",
        [format!("{keyword}%")],
        |r| r.get(0),
    )
    .unwrap()
}

fn segment_commandlog_null_sql_count(seg: &Path) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row("SELECT COUNT(*) FROM commandlog WHERE sql IS NULL", [], |r| r.get(0))
        .unwrap()
}

fn segment_commandlog_count_for_commit_starting_with(seg: &Path, commit_id: i64, keyword: &str) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row(
        "SELECT COUNT(*) FROM commandlog WHERE commit_id = ?1 AND sql LIKE ?2",
        (commit_id, format!("{keyword}%")),
        |r| r.get(0),
    )
    .unwrap()
}

fn segment_distinct_commit_ids_starting_with(seg: &Path, keyword: &str) -> std::collections::BTreeSet<i64> {
    let mut out = std::collections::BTreeSet::new();
    for p in segment_and_txn_files(seg) {
        let c = Connection::open(&p).unwrap();
        let mut stmt = c
            .prepare("SELECT DISTINCT commit_id FROM commandlog WHERE sql LIKE ?1")
            .unwrap();
        let rows = stmt
            .query_map([format!("{keyword}%")], |r| r.get::<_, i64>(0))
            .unwrap();
        for row in rows {
            out.insert(row.unwrap());
        }
    }
    out
}

fn segment_commandlog_exact_sql_count_for_commit(seg: &Path, commit_id: i64, sql: &str) -> i64 {
    let c = Connection::open(seg).unwrap();
    c.query_row(
        "SELECT COUNT(*) FROM commandlog WHERE commit_id = ?1 AND sql = ?2",
        (commit_id, sql),
        |r| r.get(0),
    )
    .unwrap()
}

fn segment_and_txn_files(seg: &Path) -> Vec<PathBuf> {
    let mut out = vec![seg.to_path_buf()];
    let Some(file_name) = seg.file_name().and_then(|s| s.to_str()) else {
        return out;
    };
    let Some(seq) = file_name.strip_suffix(".sqllog") else {
        return out;
    };
    let Some(dir) = seg.parent() else {
        return out;
    };
    let prefix = format!("{seq}.sqllog.");
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with(&prefix) && name.ends_with(".txn") {
                out.push(entry.path());
            }
        }
    }
    out
}

fn segment_and_txn_count_starting_with(seg: &Path, keyword: &str) -> i64 {
    segment_and_txn_files(seg)
        .into_iter()
        .map(|p| segment_commandlog_count_starting_with(&p, keyword))
        .sum()
}

fn segment_and_txn_ci_count_starting_with(seg: &Path, keyword: &str) -> i64 {
    segment_and_txn_files(seg)
        .into_iter()
        .map(|p| segment_commandlog_ci_count_starting_with(&p, keyword))
        .sum()
}

fn segment_and_txn_null_sql_count(seg: &Path) -> i64 {
    segment_and_txn_files(seg)
        .into_iter()
        .map(|p| segment_commandlog_null_sql_count(&p))
        .sum()
}

fn segment_and_txn_count_for_commit_starting_with(seg: &Path, commit_id: i64, keyword: &str) -> i64 {
    segment_and_txn_files(seg)
        .into_iter()
        .map(|p| segment_commandlog_count_for_commit_starting_with(&p, commit_id, keyword))
        .sum()
}

// --------------------------------------------------------------------------
// SQLite parity tests
// --------------------------------------------------------------------------

/// Core flow shared by Java `SQLiteTransactionalTest.testBasicTableOperations`
/// and `SQLiteStoreTest.testBasicTableOperations`.
fn sqlite_basic_table_operations_core(device_name: &str, test_name: &str, expect_txn_markers: bool) {
    let ws = Workspace::new(
        test_name,
        device_name,
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);
    if expect_txn_markers {
        logger.set_auto_commit(false);
    }

    // --- Transaction 1: create + batch insert -----------------------------
    logger
        .execute(
            "CREATE TABLE t_basic (id INTEGER PRIMARY KEY, name TEXT, value INTEGER)",
            &[],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_basic (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(1), ArgValue::Text("test1".into()), ArgValue::Int(100)],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_basic (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(2), ArgValue::Text("test2".into()), ArgValue::Int(200)],
        )
        .unwrap();
    logger.commit().unwrap();

    assert_eq!(count(&mut logger, "t_basic"), 2);
    let rows = logger
        .query("SELECT id, name, value FROM t_basic ORDER BY id", &[])
        .unwrap();
    assert_eq!(rows.len(), 2);
    assert_eq!(as_i64(&rows[0][0]), 1);
    assert_eq!(as_text(&rows[0][1]), "test1");
    assert_eq!(as_i64(&rows[0][2]), 100);
    assert_eq!(as_i64(&rows[1][0]), 2);
    assert_eq!(as_text(&rows[1][1]), "test2");
    assert_eq!(as_i64(&rows[1][2]), 200);

    // --- Transaction 2: update + delete -----------------------------------
    logger
        .execute(
            "UPDATE t_basic SET value = ? WHERE name = ?",
            &[ArgValue::Int(999), ArgValue::Text("test1".into())],
        )
        .unwrap();
    logger
        .execute(
            "DELETE FROM t_basic WHERE name = ?",
            &[ArgValue::Text("test2".into())],
        )
        .unwrap();
    logger.commit().unwrap();

    assert_eq!(count(&mut logger, "t_basic"), 1);
    let rows = logger
        .query("SELECT name, value FROM t_basic", &[])
        .unwrap();
    assert_eq!(rows.len(), 1);
    assert_eq!(as_text(&rows[0][0]), "test1");
    assert_eq!(as_i64(&rows[0][1]), 999);

    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    assert!(commit_id > 0);
    assert!(segment_commandlog_count_for(&seg, commit_id) > 0);

    assert_eq!(segment_commandlog_count_starting_with(&seg, "CREATE"), 1);
    assert_eq!(segment_commandlog_count_starting_with(&seg, "INSERT"), 2);
    assert_eq!(segment_commandlog_count_starting_with(&seg, "UPDATE"), 1);
    assert_eq!(segment_commandlog_count_starting_with(&seg, "DELETE"), 1);
    assert_eq!(
        segment_commandlog_count_starting_with(&seg, "BEGIN"),
        if expect_txn_markers { 2 } else { 0 }
    );
    assert_eq!(
        segment_commandlog_count_starting_with(&seg, "COMMIT"),
        if expect_txn_markers { 2 } else { 0 }
    );
}

#[test]
fn sqlite_execute_unlogged_runs_ddl_and_dml_without_commandlog_entries() {
    let ws = Workspace::new(
        "SQLiteExecuteUnlogged",
        "sqliteunlogged-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_unlogged (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .unwrap();
    logger
        .execute_unlogged(
            "INSERT INTO t_unlogged VALUES (1, 'unlogged-row')",
            &[],
        )
        .unwrap();
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "t_unlogged"), 1);
    logger.close().unwrap();

    let seg = locate_segment(&ws);
    assert_eq!(segment_commandlog_ci_count_starting_with(&seg, "CREATE TABLE t_unlogged"), 1);
    assert_eq!(segment_commandlog_ci_count_starting_with(&seg, "INSERT INTO t_unlogged"), 0);
}

/// Exact mapping: Java `SQLiteTransactionalTest.testBasicTableOperations`.
#[test]
fn sqlite_transactional_test_basic_table_operations() {
    sqlite_basic_table_operations_core(
        "sqlitetransactional-rust",
        "SQLiteTransactionalTest",
        true,
    );
}

/// Exact mapping: Java `SQLiteStoreTest.testBasicTableOperations`.
#[test]
fn sqlite_store_test_basic_table_operations() {
    sqlite_basic_table_operations_core("sqlitestore-rust", "SQLiteStoreTest", false);
}

#[test]
fn sqlite_store_rejects_non_values_and_subquery_dml_shapes() {
    let ws = Workspace::new(
        "SQLiteStoreSqlRestrictionTest",
        "sqlitestorevalidate-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute("CREATE TABLE t_store (id INTEGER, v TEXT)", &[])
        .unwrap();

    assert_execute_err_contains(
        &mut logger,
        "INSERT INTO t_store SELECT id, v FROM t_store",
        "does not allow SQL",
    );
    assert_execute_err_contains(
        &mut logger,
        "UPDATE t_store SET v = (SELECT 'x')",
        "Unsupported SQL",
    );
    assert_execute_err_contains(
        &mut logger,
        "DELETE FROM t_store WHERE id IN (SELECT id FROM t_store)",
        "Unsupported SQL",
    );

    logger.close().unwrap();
}

fn sqlite_rollback_marker_core(device_name: &str, test_name: &str, expect_rollback_marker: bool) {
    let ws = Workspace::new(test_name, device_name, "sqlite", false);
    let mut logger = open_logger(&ws);
    logger.set_auto_commit(false);

    logger
        .execute(
            "CREATE TABLE t_rb (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_rb (id, name) VALUES (?, ?)",
            &[ArgValue::Int(1), ArgValue::Text("rb".into())],
        )
        .unwrap();
    logger.rollback().unwrap();
    logger.close().unwrap();

    let seg = locate_segment(&ws);
    assert_eq!(
        segment_commandlog_count_starting_with(&seg, "ROLLBACK"),
        if expect_rollback_marker { 1 } else { 0 }
    );
}

#[test]
fn sqlite_transactional_rollback_logs_marker() {
    sqlite_rollback_marker_core(
        "sqliterollbacktxn-rust",
        "SQLiteTransactionalRollbackTest",
        true,
    );
}

#[test]
fn sqlite_store_rollback_has_no_marker() {
    sqlite_rollback_marker_core(
        "sqliterollbackstore-rust",
        "SQLiteStoreRollbackTest",
        false,
    );
}

#[test]
fn sqlite_transactional_prepared_batch_logs_sql_once_and_cleans_on_rollback() {
    let ws = Workspace::new(
        "SQLiteTransactionalPreparedBatchTest",
        "sqlitepreparedbatchtxn-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_batch (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    logger.set_auto_commit(false);

    {
        let mut stmt = logger.prepare("INSERT INTO t_batch (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.add_batch(&[ArgValue::Int(3), ArgValue::Text("c".into())]);
        stmt.execute_batch().unwrap();
    }
    logger.rollback().unwrap();

    {
        let mut stmt = logger.prepare("INSERT INTO t_batch (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(10), ArgValue::Text("ok".into())]);
        stmt.execute_batch().unwrap();
    }
    logger.commit().unwrap();
    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    assert_eq!(
        segment_commandlog_count_starting_with(&seg, "INSERT INTO t_batch"),
        2
    );
    assert_eq!(segment_commandlog_null_sql_count(&seg), 2);

    let latest_commit = segment_max_commit_id(&seg);
    assert_eq!(
        segment_commandlog_count_for_commit_starting_with(&seg, latest_commit, "INSERT INTO t_batch"),
        1
    );
}

#[test]
fn sqlite_transactional_default_autocommit_splits_create_and_batch_into_separate_txns() {
    let ws = Workspace::new(
        "SQLiteTransactionalAutoCommitBoundaryTest",
        "sqliteautocommitboundary-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    // Default wrapper behavior mirrors Java: user-autocommit is ON.
    logger
        .execute(
            "CREATE TABLE t_auto (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    {
        let mut stmt = logger.prepare("INSERT INTO t_auto (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.execute_batch().unwrap();
    }

    logger.close().unwrap();

    let seg = locate_segment(&ws);
    let ddl_commits = segment_distinct_commit_ids_starting_with(&seg, "CREATE TABLE t_auto");
    let dml_commits = segment_distinct_commit_ids_starting_with(&seg, "INSERT INTO t_auto");

    assert_eq!(ddl_commits.len(), 1, "CREATE should map to exactly one txn");
    assert_eq!(dml_commits.len(), 1, "Batch INSERT should map to exactly one txn");
    assert_ne!(
        ddl_commits.iter().next().unwrap(),
        dml_commits.iter().next().unwrap(),
        "Standalone CREATE and subsequent batch must have different commit_id values in default autocommit mode"
    );
}

#[test]
fn sqlite_store_default_autocommit_splits_create_and_batch_into_separate_txns() {
    let ws = Workspace::new(
        "SQLiteStoreAutoCommitBoundaryTest",
        "sqlitestoreautocommitboundary-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_store_auto (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    {
        let mut stmt = logger.prepare("INSERT INTO t_store_auto (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.execute_batch().unwrap();
    }

    logger.close().unwrap();

    let seg = locate_segment(&ws);
    let ddl_commits = segment_distinct_commit_ids_starting_with(&seg, "CREATE TABLE t_store_auto");
    let dml_commits = segment_distinct_commit_ids_starting_with(&seg, "INSERT INTO t_store_auto");

    assert_eq!(ddl_commits.len(), 1, "CREATE should map to exactly one txn");
    assert_eq!(dml_commits.len(), 1, "Batch INSERT should map to exactly one txn");
    assert_ne!(
        ddl_commits.iter().next().unwrap(),
        dml_commits.iter().next().unwrap(),
        "Standalone CREATE and subsequent batch must have different commit_id values in default autocommit mode"
    );
}

#[test]
fn sqlite_execute_splits_semicolon_sql_and_honors_txn_messages() {
    let ws = Workspace::new(
        "SQLiteSplitSqlExecuteTest",
        "sqlitesplitsql-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_split (id INTEGER PRIMARY KEY, v TEXT);\n             INSERT INTO t_split (id, v) VALUES (1, 'a');",
            &[],
        )
        .unwrap();

    assert_eq!(count(&mut logger, "t_split"), 1);

    logger
        .execute(
            "BEGIN; INSERT INTO t_split (id, v) VALUES (2, 'b'); ROLLBACK;",
            &[],
        )
        .unwrap();

    // Rollback should keep row-count unchanged.
    assert_eq!(count(&mut logger, "t_split"), 1);
    logger.close().unwrap();
}

/// Exact mapping: Java `SQLiteStoreAPITest.testAllAPIs`.
#[test]
fn sqlite_store_api_test_all_apis() {
    let ws = Workspace::new(
        "SQLiteStoreAPITest",
        "sqlitestoreapi-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE players (id INTEGER PRIMARY KEY, name TEXT, score INTEGER)",
            &[],
        )
        .unwrap();

    for (id, name, score) in [(1, "Alice", 100), (2, "Bob", 200)] {
        logger
            .execute(
                "INSERT INTO players (id, name, score) VALUES (?, ?, ?)",
                &[
                    ArgValue::Int(id),
                    ArgValue::Text(name.into()),
                    ArgValue::Int(score),
                ],
            )
            .unwrap();
    }
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 2);

    let alice = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Alice".into())])
        .unwrap();
    assert_eq!(as_i64(&alice[0][0]), 100);

    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(999), ArgValue::Text("Alice".into())],
        )
        .unwrap();
    let alice = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Alice".into())])
        .unwrap();
    assert_eq!(as_i64(&alice[0][0]), 999);

    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Bob".into())])
        .unwrap();
    assert_eq!(count(&mut logger, "players"), 1);

    for (id, name, score) in [(3, "Carol", 300), (4, "Dave", 400)] {
        logger
            .execute(
                "INSERT INTO players (id, name, score) VALUES (?, ?, ?)",
                &[
                    ArgValue::Int(id),
                    ArgValue::Text(name.into()),
                    ArgValue::Int(score),
                ],
            )
            .unwrap();
    }
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 3);

    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(350), ArgValue::Text("Carol".into())],
        )
        .unwrap();
    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(450), ArgValue::Text("Dave".into())],
        )
        .unwrap();
    let carol = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Carol".into())])
        .unwrap();
    assert_eq!(as_i64(&carol[0][0]), 350);
    let dave = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Dave".into())])
        .unwrap();
    assert_eq!(as_i64(&dave[0][0]), 450);

    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Carol".into())])
        .unwrap();
    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Dave".into())])
        .unwrap();
    assert_eq!(count(&mut logger, "players"), 1);

    logger.execute("DROP TABLE players", &[]).unwrap();
    logger
        .execute("CREATE TABLE players (id INTEGER PRIMARY KEY)", &[])
        .unwrap();
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 0);

    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    assert!(commit_id > 0);
    assert!(segment_commandlog_count_for(&seg, commit_id) > 0);
}

/// Verifies user-DB state survives a `close()` → reopen cycle on the
/// same `device-name`/`local-data-stage-directory`. This is the
/// "second transaction after reopen" half of the
/// `SQLiteStoreTest.testBasicTableOperations`.
///
/// Segment numbering resumes from the previous run (`commandlog-0.db`
/// finalized, second open starts at `commandlog-1.db`) and `commit_id`
/// is carried forward via `synclite_txn`.
#[test]
fn sqlite_user_db_persists_across_reopens() {
    let ws = Workspace::new(
        "SQLitePersistAcrossReopens",
        "sqlitepersist-rust",
        "sqlite",
        false,
    );

    // --- First open: create + insert + close ------------------------------
    {
        let mut logger = open_logger(&ws);
        logger
            .execute(
                "CREATE TABLE persist_t (id INTEGER PRIMARY KEY, name TEXT)",
                &[],
            )
            .unwrap();
        logger
            .execute(
                "INSERT INTO persist_t (id, name) VALUES (?, ?)",
                &[ArgValue::Int(1), ArgValue::Text("alpha".into())],
            )
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    // First segment should exist locally (no shipper).
    let seg0 = ws.stage_subdir().join("0.sqllog");
    assert!(seg0.exists(), "first segment must be present at {}", seg0.display());
    let first_commit = segment_max_commit_id(&seg0);
    assert!(first_commit > 0);

    // --- Second open: user DB persists; new segment continues -------------
    {
        let mut logger = open_logger(&ws);
        assert_eq!(count(&mut logger, "persist_t"), 1);
        let rows = logger.query("SELECT name FROM persist_t", &[]).unwrap();
        assert_eq!(as_text(&rows[0][0]), "alpha");

        // Append more data to confirm the new segment is writable.
        logger
            .execute(
                "INSERT INTO persist_t (id, name) VALUES (?, ?)",
                &[ArgValue::Int(2), ArgValue::Text("beta".into())],
            )
            .unwrap();
        logger.commit().unwrap();
        assert_eq!(count(&mut logger, "persist_t"), 2);
        logger.close().unwrap();
    }

    // Second segment present, sequence resumed at 1.
    let seg1 = ws.stage_subdir().join("1.sqllog");
    assert!(seg1.exists(), "second segment must be present at {}", seg1.display());
    let second_commit = segment_max_commit_id(&seg1);
    assert!(
        second_commit >= first_commit,
        "commit_id must be monotonic across reopens: first={first_commit} second={second_commit}"
    );
    // Second segment carries the new INSERT.
    assert_eq!(segment_commandlog_count_starting_with(&seg1, "INSERT"), 1);
    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);
}

#[test]
fn sqlite_restart_recovery_unknown_fate_with_equal_commit_appends_commit() {
    let ws = Workspace::new(
        "SQLiteRestartRecoveryEqualCommit",
        "sqliterestartequal-rust",
        "sqlite",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger.execute("CREATE TABLE t(x INTEGER)", &[]).unwrap();
        logger
            .execute("INSERT INTO t(x) VALUES (?)", &[ArgValue::Int(1)])
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    remove_fate_sql_for_commit(&seg, commit_id);

    {
        let logger = open_logger(&ws);
        logger.close().unwrap();
    }

    assert_eq!(
        segment_commandlog_exact_sql_count_for_commit(&seg, commit_id, "COMMIT"),
        1
    );
    assert_synclite_txn_matches_latest_segment(&ws);
}

#[test]
fn sqlite_restart_recovery_unknown_fate_with_higher_segment_commit_appends_rollback() {
    let ws = Workspace::new(
        "SQLiteRestartRecoveryHigherSegmentCommit",
        "sqliterestarthigher-rust",
        "sqlite",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger.execute("CREATE TABLE t(x INTEGER)", &[]).unwrap();
        logger
            .execute("INSERT INTO t(x) VALUES (?)", &[ArgValue::Int(1)])
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    remove_fate_sql_for_commit(&seg, commit_id);
    set_user_synclite_txn_commit_id(&ws, commit_id - 1);

    {
        let logger = open_logger(&ws);
        logger.close().unwrap();
    }

    assert_eq!(
        segment_commandlog_exact_sql_count_for_commit(&seg, commit_id, "ROLLBACK"),
        1
    );
    assert_eq!(
        segment_commandlog_exact_sql_count_for_commit(&seg, commit_id, "COMMIT"),
        0
    );
}

// --------------------------------------------------------------------------
// DuckDB behavior tests
// --------------------------------------------------------------------------

/// Core flow shared by Java `DuckDBTransactionalTest.testBasicTableOperations`
/// and `DuckDBStoreTest.testBasicTableOperations`.
fn duckdb_basic_table_operations_core(device_name: &str, test_name: &str) {
    let ws = Workspace::new(
        test_name,
        device_name,
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_basic (id INTEGER PRIMARY KEY, name TEXT, value INTEGER)",
            &[],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_basic (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(1), ArgValue::Text("test1".into()), ArgValue::Int(100)],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_basic (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(2), ArgValue::Text("test2".into()), ArgValue::Int(200)],
        )
        .unwrap();
    logger.commit().unwrap();

    assert_eq!(count(&mut logger, "t_basic"), 2);
    let rows = logger
        .query("SELECT id, name, value FROM t_basic ORDER BY id", &[])
        .unwrap();
    assert_eq!(rows.len(), 2);
    assert_eq!(as_i64(&rows[0][0]), 1);
    assert_eq!(as_text(&rows[0][1]), "test1");
    assert_eq!(as_i64(&rows[0][2]), 100);
    assert_eq!(as_i64(&rows[1][0]), 2);
    assert_eq!(as_text(&rows[1][1]), "test2");
    assert_eq!(as_i64(&rows[1][2]), 200);

    logger
        .execute(
            "UPDATE t_basic SET value = ? WHERE name = ?",
            &[ArgValue::Int(999), ArgValue::Text("test1".into())],
        )
        .unwrap();
    logger
        .execute(
            "DELETE FROM t_basic WHERE name = ?",
            &[ArgValue::Text("test2".into())],
        )
        .unwrap();
    logger.commit().unwrap();

    assert_eq!(count(&mut logger, "t_basic"), 1);
    let rows = logger
        .query("SELECT name, value FROM t_basic", &[])
        .unwrap();
    assert_eq!(rows.len(), 1);
    assert_eq!(as_text(&rows[0][0]), "test1");
    assert_eq!(as_i64(&rows[0][1]), 999);

    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    assert!(commit_id > 0);
    assert!(segment_commandlog_count_for(&seg, commit_id) > 0);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "CREATE"), 1);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "INSERT"), 2);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "UPDATE"), 1);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "DELETE"), 1);
}

#[test]
fn duckdb_execute_unlogged_runs_ddl_and_dml_without_commandlog_entries() {
    let ws = Workspace::new(
        "DuckDBExecuteUnlogged",
        "duckdbunlogged-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_unlogged (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .unwrap();
    logger
        .execute_unlogged(
            "INSERT INTO t_unlogged VALUES (1, 'unlogged-row')",
            &[],
        )
        .unwrap();
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "t_unlogged"), 1);
    logger.close().unwrap();

    let seg = locate_segment(&ws);
    assert!(segment_and_txn_ci_count_starting_with(&seg, "CREATE TABLE t_unlogged") >= 1);
    assert_eq!(segment_and_txn_ci_count_starting_with(&seg, "INSERT INTO t_unlogged"), 0);
}

/// Exact mapping: Java `DuckDBTransactionalTest.testBasicTableOperations`.
#[test]
fn duckdb_transactional_test_basic_table_operations() {
    duckdb_basic_table_operations_core(
        "duckdbtransactional-rust",
        "DuckDBTransactionalTest",
    );
}

/// Exact mapping: Java `DuckDBStoreTest.testBasicTableOperations`.
#[test]
fn duckdb_store_test_basic_table_operations() {
    duckdb_basic_table_operations_core("duckdbstore-rust", "DuckDBStoreTest");
}

#[test]
fn duckdb_store_rejects_non_values_and_subquery_dml_shapes() {
    let ws = Workspace::new(
        "DuckDBStoreSqlRestrictionTest",
        "duckdbstorevalidate-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute("CREATE TABLE t_store (id INTEGER, v TEXT)", &[])
        .unwrap();

    assert_execute_err_contains(
        &mut logger,
        "INSERT INTO t_store SELECT id, v FROM t_store",
        "does not allow SQL",
    );
    assert_execute_err_contains(
        &mut logger,
        "UPDATE t_store SET v = (SELECT 'x')",
        "Unsupported SQL",
    );
    assert_execute_err_contains(
        &mut logger,
        "DELETE FROM t_store WHERE id IN (SELECT id FROM t_store)",
        "Unsupported SQL",
    );

    logger.close().unwrap();
}

fn duckdb_rollback_marker_core(device_name: &str, test_name: &str, expect_rollback_marker: bool) {
    let ws = Workspace::new(test_name, device_name, "duckdb", false);
    let mut logger = open_logger(&ws);
    logger.set_auto_commit(false);

    logger
        .execute(
            "CREATE TABLE t_rb (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_rb (id, name) VALUES (?, ?)",
            &[ArgValue::Int(1), ArgValue::Text("rb".into())],
        )
        .unwrap();
    logger.rollback().unwrap();
    logger.close().unwrap();

    if let Some(seg) = try_locate_segment(&ws) {
        assert_eq!(
            segment_commandlog_count_starting_with(&seg, "ROLLBACK"),
            if expect_rollback_marker { 1 } else { 0 }
        );
    } else {
        assert!(
            !expect_rollback_marker,
            "transactional rollback must emit a non-empty segment with ROLLBACK marker"
        );
    }
}

#[test]
fn duckdb_transactional_rollback_logs_marker() {
    duckdb_rollback_marker_core(
        "duckdbrollbacktxn-rust",
        "DuckDBTransactionalRollbackTest",
        true,
    );
}

#[test]
fn duckdb_store_rollback_has_no_marker() {
    duckdb_rollback_marker_core(
        "duckdbrollbackstore-rust",
        "DuckDBStoreRollbackTest",
        false,
    );
}

#[test]
fn duckdb_transactional_prepared_batch_logs_sql_once_and_cleans_on_rollback() {
    let ws = Workspace::new(
        "DuckDBTransactionalPreparedBatchTest",
        "duckdbpreparedbatchtxn-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_batch (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    logger.set_auto_commit(false);

    {
        let mut stmt = logger.prepare("INSERT INTO t_batch (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.add_batch(&[ArgValue::Int(3), ArgValue::Text("c".into())]);
        stmt.execute_batch().unwrap();
    }
    logger.rollback().unwrap();

    {
        let mut stmt = logger.prepare("INSERT INTO t_batch (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(10), ArgValue::Text("ok".into())]);
        stmt.execute_batch().unwrap();
    }
    logger.commit().unwrap();
    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    assert_eq!(
        segment_and_txn_count_starting_with(&seg, "INSERT INTO t_batch"),
        1
    );
    assert_eq!(segment_and_txn_null_sql_count(&seg), 0);

    let latest_commit = segment_max_commit_id(&seg);
    assert_eq!(
        segment_and_txn_count_for_commit_starting_with(&seg, latest_commit, "INSERT INTO t_batch"),
        1
    );
}

#[test]
fn duckdb_store_default_autocommit_splits_create_and_batch_into_separate_txns() {
    let ws = Workspace::new(
        "DuckDBStoreAutoCommitBoundaryTest",
        "duckdbstoreautocommitboundary-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_store_auto (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    {
        let mut stmt = logger.prepare("INSERT INTO t_store_auto (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.execute_batch().unwrap();
    }

    logger.close().unwrap();

    let seg = locate_segment(&ws);
    let ddl_commits = segment_distinct_commit_ids_starting_with(&seg, "CREATE TABLE t_store_auto");
    let dml_commits = segment_distinct_commit_ids_starting_with(&seg, "INSERT INTO t_store_auto");

    assert_eq!(ddl_commits.len(), 1, "CREATE should map to exactly one txn");
    assert_eq!(dml_commits.len(), 1, "Batch INSERT should map to exactly one txn");
    assert_ne!(
        ddl_commits.iter().next().unwrap(),
        dml_commits.iter().next().unwrap(),
        "Standalone CREATE and subsequent batch must have different commit_id values in default autocommit mode"
    );
}

#[test]
fn duckdb_store_manual_txn_uses_master_and_txn_files_without_txn_markers() {
    let ws = Workspace::new(
        "DuckDBStoreTxnFileSchemeTest",
        "duckdbstoretxnscheme-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_store_txn (id INTEGER PRIMARY KEY, v TEXT)",
            &[],
        )
        .unwrap();

    logger.set_auto_commit(false);
    {
        let mut stmt = logger.prepare("INSERT INTO t_store_txn (id, v) VALUES (?, ?)");
        stmt.add_batch(&[ArgValue::Int(1), ArgValue::Text("a".into())]);
        stmt.add_batch(&[ArgValue::Int(2), ArgValue::Text("b".into())]);
        stmt.execute_batch().unwrap();
    }
    logger.commit().unwrap();
    logger.close().unwrap();

    let seg = locate_segment(&ws);
    let files = segment_and_txn_files(&seg);
    assert!(
        files.len() >= 3,
        "Expected master segment + txn files for CREATE autocommit and manual batch commit"
    );

    assert_eq!(
        segment_and_txn_count_starting_with(&seg, "REPLAY_TXN"),
        2,
        "Store path should publish one REPLAY_TXN per committed transaction"
    );
    assert_eq!(segment_and_txn_count_starting_with(&seg, "BEGIN"), 0);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "COMMIT"), 0);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "ROLLBACK"), 0);
}

#[test]
fn duckdb_store_execute_splits_semicolon_sql_and_honors_txn_messages() {
    let ws = Workspace::new(
        "DuckDBStoreSplitSqlExecuteTest",
        "duckdbstoresplitsql-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE t_split (id INTEGER PRIMARY KEY, v TEXT);\n             INSERT INTO t_split (id, v) VALUES (1, 'a');",
            &[],
        )
        .unwrap();

    assert_eq!(count(&mut logger, "t_split"), 1);

    logger
        .execute(
            "BEGIN; INSERT INTO t_split (id, v) VALUES (2, 'b'); ROLLBACK;",
            &[],
        )
        .unwrap();

    assert_eq!(count(&mut logger, "t_split"), 1);
    logger.close().unwrap();
}

#[test]
fn duckdb_shadow_schema_rebuilt_on_reopen() {
    let ws = Workspace::new(
        "DuckDBShadowSchemaRebuild",
        "duckdbshadow-rust",
        "duckdb",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger
            .execute("CREATE TABLE t_shadow (id INTEGER PRIMARY KEY, name TEXT)", &[])
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let shadow_path = ws.sqlite_shadow_schema();
    assert!(shadow_path.exists(), "shadow schema file missing: {}", shadow_path.display());

    let shadow = Connection::open(&shadow_path).unwrap();
    let count: i64 = shadow
        .query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='t_shadow'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(count, 1, "shadow schema missing table after initial sync");

    drop(shadow);
    fs::remove_file(&shadow_path).unwrap();
    assert!(!shadow_path.exists());

    {
        let logger = open_logger(&ws);
        logger.close().unwrap();
    }

    let rebuilt = Connection::open(&shadow_path).unwrap();
    let rebuilt_count: i64 = rebuilt
        .query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='t_shadow'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(rebuilt_count, 1, "shadow schema was not rebuilt from DuckDB on reopen");
}

/// Exact mapping: Java `DuckDBStoreAPITest.testAllAPIs`.
#[test]
fn duckdb_store_api_test_all_apis() {
    let ws = Workspace::new(
        "DuckDBStoreAPITest",
        "duckdbstoreapi-rust",
        "duckdb",
        false,
    );
    let mut logger = open_logger(&ws);

    logger
        .execute(
            "CREATE TABLE players (id INTEGER PRIMARY KEY, name TEXT, score INTEGER)",
            &[],
        )
        .unwrap();

    for (id, name, score) in [(1, "Alice", 100), (2, "Bob", 200)] {
        logger
            .execute(
                "INSERT INTO players (id, name, score) VALUES (?, ?, ?)",
                &[
                    ArgValue::Int(id),
                    ArgValue::Text(name.into()),
                    ArgValue::Int(score),
                ],
            )
            .unwrap();
    }
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 2);

    let alice = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Alice".into())])
        .unwrap();
    assert_eq!(as_i64(&alice[0][0]), 100);

    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(999), ArgValue::Text("Alice".into())],
        )
        .unwrap();
    let alice = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Alice".into())])
        .unwrap();
    assert_eq!(as_i64(&alice[0][0]), 999);

    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Bob".into())])
        .unwrap();
    assert_eq!(count(&mut logger, "players"), 1);

    for (id, name, score) in [(3, "Carol", 300), (4, "Dave", 400)] {
        logger
            .execute(
                "INSERT INTO players (id, name, score) VALUES (?, ?, ?)",
                &[
                    ArgValue::Int(id),
                    ArgValue::Text(name.into()),
                    ArgValue::Int(score),
                ],
            )
            .unwrap();
    }
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 3);

    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(350), ArgValue::Text("Carol".into())],
        )
        .unwrap();
    logger
        .execute(
            "UPDATE players SET score = ? WHERE name = ?",
            &[ArgValue::Int(450), ArgValue::Text("Dave".into())],
        )
        .unwrap();
    let carol = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Carol".into())])
        .unwrap();
    assert_eq!(as_i64(&carol[0][0]), 350);
    let dave = logger
        .query("SELECT score FROM players WHERE name = ?", &[ArgValue::Text("Dave".into())])
        .unwrap();
    assert_eq!(as_i64(&dave[0][0]), 450);

    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Carol".into())])
        .unwrap();
    logger
        .execute("DELETE FROM players WHERE name = ?", &[ArgValue::Text("Dave".into())])
        .unwrap();
    assert_eq!(count(&mut logger, "players"), 1);

    logger.execute("DROP TABLE players", &[]).unwrap();
    logger
        .execute("CREATE TABLE players (id INTEGER PRIMARY KEY)", &[])
        .unwrap();
    logger.commit().unwrap();
    assert_eq!(count(&mut logger, "players"), 0);

    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    assert!(commit_id > 0);
    assert!(segment_commandlog_count_for(&seg, commit_id) > 0);
}

/// DuckDB equivalent of [`sqlite_user_db_persists_across_reopens`].
#[test]
fn duckdb_user_db_persists_across_reopens() {
    let ws = Workspace::new(
        "DuckDBPersistAcrossReopens",
        "duckdbpersist-rust",
        "duckdb",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger
            .execute(
                "CREATE TABLE persist_t (id INTEGER PRIMARY KEY, name TEXT)",
                &[],
            )
            .unwrap();
        logger
            .execute(
                "INSERT INTO persist_t (id, name) VALUES (?, ?)",
                &[ArgValue::Int(1), ArgValue::Text("alpha".into())],
            )
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let seg0 = ws.stage_subdir().join("0.sqllog");
    assert!(seg0.exists(), "first segment must be present at {}", seg0.display());
    let first_commit = segment_max_commit_id(&seg0);
    assert!(first_commit > 0);

    {
        let mut logger = open_logger(&ws);
        assert_eq!(count(&mut logger, "persist_t"), 1);
        let rows = logger.query("SELECT name FROM persist_t", &[]).unwrap();
        assert_eq!(as_text(&rows[0][0]), "alpha");

        logger
            .execute(
                "INSERT INTO persist_t (id, name) VALUES (?, ?)",
                &[ArgValue::Int(2), ArgValue::Text("beta".into())],
            )
            .unwrap();
        logger.commit().unwrap();
        assert_eq!(count(&mut logger, "persist_t"), 2);
        logger.close().unwrap();
    }

    let seg1 = ws.stage_subdir().join("1.sqllog");
    assert!(seg1.exists(), "second segment must be present at {}", seg1.display());
    let second_commit = segment_max_commit_id(&seg1);
    assert!(
        second_commit >= first_commit,
        "commit_id must be monotonic across reopens: first={first_commit} second={second_commit}"
    );
    assert_eq!(segment_and_txn_count_starting_with(&seg1, "INSERT"), 1);
    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);
}

#[test]
fn duckdb_reopen_without_writes_does_not_ship_empty_segment() {
    let ws = Workspace::new(
        "DuckDBNoEmptySegmentOnNoopReopen",
        "duckdbnoempty-rust",
        "duckdb",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger
            .execute("CREATE TABLE t_empty_guard (id INTEGER PRIMARY KEY)", &[])
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let seg0 = ws.stage_subdir().join("0.sqllog");
    assert!(seg0.exists(), "expected first segment at {}", seg0.display());

    {
        let logger = open_logger(&ws);
        logger.close().unwrap();
    }

    let seg1 = ws.stage_subdir().join("1.sqllog");
    assert!(
        !seg1.exists(),
        "empty segment must not be shipped or left behind: {}",
        seg1.display()
    );
}

#[test]
fn duckdb_restart_recovery_unknown_fate_with_equal_commit_appends_commit() {
    let ws = Workspace::new(
        "DuckDBRestartRecoveryEqualCommit",
        "duckdbrestartequal-rust",
        "duckdb",
        false,
    );

    {
        let mut logger = open_logger(&ws);
        logger.execute("CREATE TABLE t(x INTEGER)", &[]).unwrap();
        logger
            .execute("INSERT INTO t(x) VALUES (?)", &[ArgValue::Int(1)])
            .unwrap();
        logger.commit().unwrap();
        logger.close().unwrap();
    }

    let seg = locate_segment(&ws);
    let commit_id = segment_max_commit_id(&seg);
    remove_fate_sql_for_commit(&seg, commit_id);

    {
        let logger = open_logger(&ws);
        logger.close().unwrap();
    }

    assert_eq!(
        segment_commandlog_exact_sql_count_for_commit(&seg, commit_id, "COMMIT"),
        1
    );
    assert_synclite_txn_matches_latest_segment(&ws);
}


// --------------------------------------------------------------------------
// Layout behavior (BackupAgent + LogMover)
// --------------------------------------------------------------------------

#[test]
fn sqlite_sql_device_init_with_preexisting_data_keeps_backup_and_logs_new_writes() {
    preexisting_data_init_backup_and_logging_core(
        "sqlite",
        "sqlitepreexistingsql-rust",
        "SQLitePreexistingSqlInitBackupTest",
    );
}

#[test]
fn sqlite_store_device_init_with_preexisting_data_keeps_backup_and_logs_new_writes() {
    preexisting_data_init_backup_and_logging_core(
        "sqlite",
        "sqlitepreexistingstore-rust",
        "SQLitePreexistingStoreInitBackupTest",
    );
}

#[test]
fn duckdb_sql_device_init_with_preexisting_data_keeps_backup_and_logs_new_writes() {
    preexisting_data_init_backup_and_logging_core(
        "duckdb",
        "duckdbpreexistingsql-rust",
        "DuckDBPreexistingSqlInitBackupTest",
    );
}

#[test]
fn duckdb_store_device_init_with_preexisting_data_keeps_backup_and_logs_new_writes() {
    preexisting_data_init_backup_and_logging_core(
        "duckdb",
        "duckdbpreexistingstore-rust",
        "DuckDBPreexistingStoreInitBackupTest",
    );
}

/// After `Logger::open`, the device home and stage subdir must
/// exist, with metadata + backup files inside the stage subdir, and the
/// segment file landed as `<N>.sqllog`.
#[test]
fn sqlite_layout_behavior() {
    let ws = Workspace::new(
        "SQLiteLayoutParity",
        "sqlitelayout-rust",
        "sqlite",
        false,
    );
    let mut logger = open_logger(&ws);
    logger.execute("CREATE TABLE t(x INTEGER)", &[]).unwrap();
    logger.commit().unwrap();
    logger.close().unwrap();

    // Device home <db_path>.synclite/ exists with metadata file.
    let device_home = ws.device_home();
    assert!(device_home.exists(), "device home missing: {}", device_home.display());
    let local_meta = device_home.join("sqlitelayout-rust.db.synclite.metadata");
    assert!(local_meta.exists(), "metadata file missing: {}", local_meta.display());

    // Local backup file was cleaned post-ship.
    let local_backup = device_home.join("sqlitelayout-rust.db.synclite.backup");
    assert!(!local_backup.exists(), "local backup should be cleaned");

    // Stage subdir `synclite-<effective-device-name>-<uuid>` exists with the
    // staged backup, metadata copy, and the 0.sqllog segment.
    let stage_subdir = ws.stage_subdir();
    assert!(stage_subdir.join("sqlitelayout-rust.db.synclite.backup").exists());
    assert!(stage_subdir.join("sqlitelayout-rust.db.synclite.metadata").exists());
    assert!(stage_subdir.join("0.sqllog").exists());

    // UUID is recorded in local metadata.
    let c = Connection::open(&local_meta).unwrap();
    let uuid: String = c
        .query_row("SELECT value FROM metadata WHERE key='uuid'", [], |r| r.get(0))
        .unwrap();
    assert!(!uuid.is_empty());
    let device_type: String = c
        .query_row("SELECT value FROM metadata WHERE key='device_type'", [], |r| r.get(0))
        .unwrap();
    assert_eq!(device_type, "SQLITE");
    let database_name: String = c
        .query_row("SELECT value FROM metadata WHERE key='database_name'", [], |r| r.get(0))
        .unwrap();
    assert_eq!(database_name, "sqlitelayout-rust.db");

    // The backup snapshot itself should contain the txn table, matching
    // the Java flow that creates synclite_txn before backup.
    let backup = stage_subdir.join("sqlitelayout-rust.db.synclite.backup");
    assert!(backup.exists(), "backup file missing: {}", backup.display());
    let backup_conn = Connection::open(&backup).unwrap();
    let txn_tables: i64 = backup_conn
        .query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='synclite_txn'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(txn_tables, 1);

    // Stage subdir name carries the same uuid.
    let subdir_name = stage_subdir.file_name().unwrap().to_string_lossy().into_owned();
    assert_eq!(subdir_name, format!("synclite-{}-{uuid}", ws.device_name));
}

// --------------------------------------------------------------------------
// Explicit scoped-gap placeholders (Streaming)
// --------------------------------------------------------------------------

#[test]
fn streaming_test_basic_table_operations() {
    let ws = Workspace::new("StreamingTest", "streaming-rust", "sqlite", false);
    let mut logger = open_logger(&ws);
    logger.set_auto_commit(false);

    logger
        .execute(
            "CREATE TABLE t_stream (id INTEGER PRIMARY KEY, name TEXT, value INTEGER)",
            &[],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_stream (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(1), ArgValue::Text("s1".into()), ArgValue::Int(10)],
        )
        .unwrap();
    logger
        .execute(
            "INSERT INTO t_stream (id, name, value) VALUES (?, ?, ?)",
            &[ArgValue::Int(2), ArgValue::Text("s2".into()), ArgValue::Int(20)],
        )
        .unwrap();
    assert_execute_err_contains(
        &mut logger,
        "UPDATE t_stream SET value = 11 WHERE id = 1",
        "streaming device does not allow SQL",
    );
    assert_execute_err_contains(
        &mut logger,
        "DELETE FROM t_stream WHERE id = 2",
        "streaming device does not allow SQL",
    );

    logger.commit().unwrap();

    // Streaming device does not persist user DML rows into the SQLite file.
    assert_eq!(count(&mut logger, "t_stream"), 0);
    logger.close().unwrap();

    assert_latest_segment_carries_max_commit_id(&ws);
    assert_synclite_txn_matches_latest_segment(&ws);

    let seg = locate_segment(&ws);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "CREATE"), 1);
    assert_eq!(segment_and_txn_count_starting_with(&seg, "INSERT"), 2);
    assert_eq!(segment_commandlog_count_starting_with(&seg, "REPLAY_TXN"), 1);
}

